<?php

namespace DoctrineProxies\__CG__\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ECreation extends \Entity\ECreation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\ECreation' . "\0" . 'id', '' . "\0" . 'Entity\\ECreation' . "\0" . 'title', '' . "\0" . 'Entity\\ECreation' . "\0" . 'description', '' . "\0" . 'Entity\\ECreation' . "\0" . 'accessories', '' . "\0" . 'Entity\\ECreation' . "\0" . 'createdAt', '' . "\0" . 'Entity\\ECreation' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\ECreation' . "\0" . 'author', '' . "\0" . 'Entity\\ECreation' . "\0" . 'images', '' . "\0" . 'Entity\\ECreation' . "\0" . 'comments', '' . "\0" . 'Entity\\ECreation' . "\0" . 'likes', '' . "\0" . 'Entity\\ECreation' . "\0" . 'savedBy', '' . "\0" . 'Entity\\ECreation' . "\0" . 'yarn', '' . "\0" . 'Entity\\ECreation' . "\0" . 'yarnWeight', '' . "\0" . 'Entity\\ECreation' . "\0" . 'crochet', '' . "\0" . 'Entity\\ECreation' . "\0" . 'category'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\ECreation' . "\0" . 'id', '' . "\0" . 'Entity\\ECreation' . "\0" . 'title', '' . "\0" . 'Entity\\ECreation' . "\0" . 'description', '' . "\0" . 'Entity\\ECreation' . "\0" . 'accessories', '' . "\0" . 'Entity\\ECreation' . "\0" . 'createdAt', '' . "\0" . 'Entity\\ECreation' . "\0" . 'updatedAt', '' . "\0" . 'Entity\\ECreation' . "\0" . 'author', '' . "\0" . 'Entity\\ECreation' . "\0" . 'images', '' . "\0" . 'Entity\\ECreation' . "\0" . 'comments', '' . "\0" . 'Entity\\ECreation' . "\0" . 'likes', '' . "\0" . 'Entity\\ECreation' . "\0" . 'savedBy', '' . "\0" . 'Entity\\ECreation' . "\0" . 'yarn', '' . "\0" . 'Entity\\ECreation' . "\0" . 'yarnWeight', '' . "\0" . 'Entity\\ECreation' . "\0" . 'crochet', '' . "\0" . 'Entity\\ECreation' . "\0" . 'category'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ECreation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessories(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessories', []);

        return parent::getAccessories();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessories(?string $accessories): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessories', [$accessories]);

        parent::setAccessories($accessories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', []);

        parent::setUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor(): \Entity\EUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor(\Entity\EUser $author): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Entity\EImage $image): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Entity\EImage $image): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\Entity\EComment $comment): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getLikes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikes', []);

        return parent::getLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLike(\Entity\ELike $like): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLike', [$like]);

        parent::addLike($like);
    }

    /**
     * {@inheritDoc}
     */
    public function getSavedBy(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSavedBy', []);

        return parent::getSavedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function addSavedBy(\Entity\EUser $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSavedBy', [$user]);

        parent::addSavedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getYarn(): \Entity\EYarn
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYarn', []);

        return parent::getYarn();
    }

    /**
     * {@inheritDoc}
     */
    public function setYarn(\Entity\EYarn $yarn): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYarn', [$yarn]);

        parent::setYarn($yarn);
    }

    /**
     * {@inheritDoc}
     */
    public function getYarnWeight(): \Entity\EYarnWeight
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYarnWeight', []);

        return parent::getYarnWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setYarnWeight(\Entity\EYarnWeight $yarnWeight): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYarnWeight', [$yarnWeight]);

        parent::setYarnWeight($yarnWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrochet(): \Entity\ECrochet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrochet', []);

        return parent::getCrochet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCrochet(\Entity\ECrochet $crochet): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrochet', [$crochet]);

        parent::setCrochet($crochet);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): \Entity\ECategory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Entity\ECategory $category): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getLikesCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikesCount', []);

        return parent::getLikesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentCount', []);

        return parent::getCommentCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getSavedCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSavedCount', []);

        return parent::getSavedCount();
    }

}
