<?php

namespace DoctrineProxies\__CG__\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EUser extends \Entity\EUser implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\EUser' . "\0" . 'id', '' . "\0" . 'Entity\\EUser' . "\0" . 'username', '' . "\0" . 'Entity\\EUser' . "\0" . 'email', '' . "\0" . 'Entity\\EUser' . "\0" . 'passwordHash', '' . "\0" . 'Entity\\EUser' . "\0" . 'bio', '' . "\0" . 'Entity\\EUser' . "\0" . 'avatarPath', '' . "\0" . 'Entity\\EUser' . "\0" . 'role', '' . "\0" . 'Entity\\EUser' . "\0" . 'createdAt', '' . "\0" . 'Entity\\EUser' . "\0" . 'creations', '' . "\0" . 'Entity\\EUser' . "\0" . 'comments', '' . "\0" . 'Entity\\EUser' . "\0" . 'likes', '' . "\0" . 'Entity\\EUser' . "\0" . 'savedCreations', '' . "\0" . 'Entity\\EUser' . "\0" . 'following', '' . "\0" . 'Entity\\EUser' . "\0" . 'followers'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\EUser' . "\0" . 'id', '' . "\0" . 'Entity\\EUser' . "\0" . 'username', '' . "\0" . 'Entity\\EUser' . "\0" . 'email', '' . "\0" . 'Entity\\EUser' . "\0" . 'passwordHash', '' . "\0" . 'Entity\\EUser' . "\0" . 'bio', '' . "\0" . 'Entity\\EUser' . "\0" . 'avatarPath', '' . "\0" . 'Entity\\EUser' . "\0" . 'role', '' . "\0" . 'Entity\\EUser' . "\0" . 'createdAt', '' . "\0" . 'Entity\\EUser' . "\0" . 'creations', '' . "\0" . 'Entity\\EUser' . "\0" . 'comments', '' . "\0" . 'Entity\\EUser' . "\0" . 'likes', '' . "\0" . 'Entity\\EUser' . "\0" . 'savedCreations', '' . "\0" . 'Entity\\EUser' . "\0" . 'following', '' . "\0" . 'Entity\\EUser' . "\0" . 'followers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EUser $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordHash(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordHash', []);

        return parent::getPasswordHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordHash(string $hash): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordHash', [$hash]);

        parent::setPasswordHash($hash);
    }

    /**
     * {@inheritDoc}
     */
    public function getBio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBio', []);

        return parent::getBio();
    }

    /**
     * {@inheritDoc}
     */
    public function setBio(?string $bio): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBio', [$bio]);

        parent::setBio($bio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatarPath(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatarPath', []);

        return parent::getAvatarPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatarPath(?string $path): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatarPath', [$path]);

        parent::setAvatarPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(string $role): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreations', []);

        return parent::getCreations();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreation(\Entity\ECreation $creation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreation', [$creation]);

        parent::addCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreation(\Entity\ECreation $creation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreation', [$creation]);

        parent::removeCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function getLikes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLikes', []);

        return parent::getLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function getSavedCreations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSavedCreations', []);

        return parent::getSavedCreations();
    }

    /**
     * {@inheritDoc}
     */
    public function addSavedCreation(\Entity\ECreation $creation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSavedCreation', [$creation]);

        parent::addSavedCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSavedCreation(\Entity\ECreation $creation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSavedCreation', [$creation]);

        parent::removeSavedCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowing(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowing', []);

        return parent::getFollowing();
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowers', []);

        return parent::getFollowers();
    }

    /**
     * {@inheritDoc}
     */
    public function follow(\Entity\EUser $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'follow', [$user]);

        parent::follow($user);
    }

    /**
     * {@inheritDoc}
     */
    public function unfollow(\Entity\EUser $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unfollow', [$user]);

        parent::unfollow($user);
    }

    /**
     * {@inheritDoc}
     */
    public function isFollowing(\Entity\Euser $user): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFollowing', [$user]);

        return parent::isFollowing($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowerCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowerCount', []);

        return parent::getFollowerCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowingCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowingCount', []);

        return parent::getFollowingCount();
    }

}
